#!/usr/bin/env bash
#
# update-skills.sh — sync centralized skills + rules into a project.
#
# Run from a project directory (the Makefile does this after cloning the repo):
#   scripts/update-skills.sh [--type kmp|backend|ios|other] [--project DIR]
#
# Behavior:
#   * Asks the project type (unless --type given) and resolves its categories
#     from project-types.conf.
#   * Installs every skill in those categories into <project>/.claude/skills/
#     and every rule into <project>/.claude/rules/, both verbatim, and generates
#     a thin-pointer Cursor rule in <project>/.cursor/rules/ for each.
#   * Removes ONLY what a previous run installed (tracked in a manifest), so
#     project-specific skills and hand-written rules are preserved.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILLS_ROOT="$REPO_DIR/skills"
RULES_ROOT="$REPO_DIR/rules"
TYPES_CONF="$REPO_DIR/project-types.conf"

PROJECT_DIR="$PWD"
TYPE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --type)    TYPE="$2"; shift 2 ;;
    --project) PROJECT_DIR="$(cd "$2" && pwd)"; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -f "$TYPES_CONF" ]] || { echo "missing $TYPES_CONF" >&2; exit 1; }
if [[ "$PROJECT_DIR" == "$REPO_DIR" ]]; then
  echo "refusing to install into the skills repo itself" >&2; exit 1
fi

available_types() { grep -vE '^[[:space:]]*#|^[[:space:]]*$' "$TYPES_CONF" | sed -E 's/:.*//' | tr -d ' '; }
categories_for()  { grep -E "^[[:space:]]*$1[[:space:]]*:" "$TYPES_CONF" | sed -E 's/^[^:]*:[[:space:]]*//'; }

# --- pick type ------------------------------------------------------------
if [[ -z "$TYPE" ]]; then
  echo "Project: $PROJECT_DIR"
  echo "Available types: $(available_types | paste -sd' ' -)"
  printf "Project type? " > /dev/tty
  read -r TYPE < /dev/tty
fi
CATEGORIES="$(categories_for "$TYPE")"
[[ -n "$CATEGORIES" ]] || { echo "unknown type '$TYPE' (have: $(available_types | paste -sd', ' -))" >&2; exit 1; }
echo "Type '$TYPE' -> categories: $CATEGORIES"

CLAUDE_SKILLS="$PROJECT_DIR/.claude/skills"
CLAUDE_RULES="$PROJECT_DIR/.claude/rules"
CURSOR_RULES="$PROJECT_DIR/.cursor/rules"
MANIFEST="$CLAUDE_SKILLS/.managed"
META_RULE="claude-skills-source-of-truth.mdc"
RULES_INDEX="fosh-labs-conventions.md"

# --- remove what a previous run installed --------------------------------
if [[ -f "$MANIFEST" ]]; then
  while IFS= read -r line; do
    case "$line" in
      skill:*)       rm -rf "$CLAUDE_SKILLS/${line#skill:}" ;;
      rule:*)        rm -f  "$CURSOR_RULES/${line#rule:}" ;;
      claude-rule:*) rm -f  "$CLAUDE_RULES/${line#claude-rule:}" ;;
    esac
  done < "$MANIFEST"
  rm -f "$MANIFEST"
fi

mkdir -p "$CLAUDE_SKILLS" "$CLAUDE_RULES" "$CURSOR_RULES"

# --- frontmatter helpers --------------------------------------------------
get_desc()  { sed -n 's/^description:[[:space:]]*//p' "$1" | head -1; }
get_title() { sed -n 's/^# //p' "$1" | head -1; }

# The `paths:` globs from the first frontmatter block, comma-joined for Cursor.
get_globs() {
  awk '
    NR==1 && /^---[[:space:]]*$/ { fm=1; next }
    fm && /^---[[:space:]]*$/    { exit }
    fm && /^paths:[[:space:]]*$/ { inp=1; next }
    inp && /^[[:space:]]+-/ {
      v=$0; sub(/^[[:space:]]*-[[:space:]]*/,"",v); gsub(/"/,"",v); gsub(/[[:space:]]+$/,"",v)
      g = g (g==""?"":",") v; next
    }
    inp && /^[^[:space:]]/ { exit }
    END { print g }
  ' "$1"
}

# write_cursor_pointer <name> <description> <globs> <alwaysApply> <target-path>
write_cursor_pointer() {
  local name="$1" desc="$2" globs="$3" always="$4" target="$5"
  {
    echo "---"
    echo "description: $desc"
    [[ -n "$globs" ]] && echo "globs: $globs"
    echo "alwaysApply: $always"
    echo "---"
    echo ""
    echo "# $name"
    echo ""
    echo "This convention is authored for Claude Code (the source of truth): \`$target\`."
    echo ""
    echo "**Read that file and follow it fully.** Do not duplicate its content here;"
    echo "edit that file, not this rule. Generated by fosh-labs/skills."
  } > "$CURSOR_RULES/$name.mdc"
  INSTALLED_RULES+=("$name.mdc")
}

# --- install selected skills + rules --------------------------------------
declare -a INSTALLED_SKILLS=()
declare -a INSTALLED_CLAUDE_RULES=()
declare -a INSTALLED_RULES=()

for cat in $CATEGORIES; do
  skills_dir="$SKILLS_ROOT/$cat"
  rules_dir="$RULES_ROOT/$cat"
  [[ -d "$skills_dir" || -d "$rules_dir" ]] || { echo "  (no such category: $cat — skipping)"; continue; }

  for skill_md in "$skills_dir"/*/SKILL.md; do
    [[ -e "$skill_md" ]] || continue
    name="$(basename "$(dirname "$skill_md")")"
    if grep -q '^paths:' "$skill_md"; then
      echo "  warning: skill $name has paths: — a convention that applies on its own belongs in rules/" >&2
    fi
    mkdir -p "$CLAUDE_SKILLS/$name"
    cp "$skill_md" "$CLAUDE_SKILLS/$name/SKILL.md"
    INSTALLED_SKILLS+=("$name")
    desc="$(get_desc "$skill_md")"
    write_cursor_pointer "$name" "${desc:-See .claude/skills/$name/SKILL.md}" "" false ".claude/skills/$name/SKILL.md"
  done

  for rule_md in "$rules_dir"/*.md; do
    [[ -e "$rule_md" ]] || continue
    name="$(basename "$rule_md" .md)"
    globs="$(get_globs "$rule_md")"
    if grep -q '^paths:' "$rule_md" && [[ -z "$globs" ]]; then
      echo "  warning: rule $name — paths: must be a YAML list inside a closed frontmatter block" >&2
    fi
    cp "$rule_md" "$CLAUDE_RULES/$name.md"
    INSTALLED_CLAUDE_RULES+=("$name.md")
    title="$(get_title "$rule_md")"
    always=false; [[ -z "$globs" ]] && always=true
    write_cursor_pointer "$name" "${title:-See .claude/rules/$name.md}" "$globs" "$always" ".claude/rules/$name.md"
  done
done

# --- index rule: where the conventions live (skills refer to them by name) --
{
  echo "# fosh-labs conventions"
  echo ""
  echo "Project conventions are rules in \`.claude/rules/\`. A rule with \`paths:\` is in"
  echo "context whenever a matching file is read; when a skill points you to one by name"
  echo "and it is not in context yet, read it before writing:"
  echo ""
  for rule in "${INSTALLED_CLAUDE_RULES[@]}"; do
    echo "- \`${rule%.md}\` — \`.claude/rules/$rule\`"
  done
} > "$CLAUDE_RULES/$RULES_INDEX"
INSTALLED_CLAUDE_RULES+=("$RULES_INDEX")

# --- meta rule: skills + rules are source of truth (Cursor) ---------------
{
  echo "---"
  echo "description: Claude Code skills and rules in .claude/ are the canonical project conventions"
  echo "alwaysApply: true"
  echo "---"
  echo ""
  echo "# Claude Code skills and rules (source of truth)"
  echo ""
  echo "Project conventions are authored for Claude Code in \`.claude/skills/*/SKILL.md\`"
  echo "(workflows) and \`.claude/rules/*.md\` (conventions). The Cursor rules here only"
  echo "point to those files — never duplicate their content."
  echo ""
  echo "| Name | File |"
  echo "|------|------|"
  for name in "${INSTALLED_SKILLS[@]}"; do
    echo "| $name | \`.claude/skills/$name/SKILL.md\` |"
  done
  for rule in "${INSTALLED_CLAUDE_RULES[@]}"; do
    echo "| ${rule%.md} | \`.claude/rules/$rule\` |"
  done
  echo ""
  echo "When a task matches one, read that file first and follow it fully."
  echo "Edit conventions in \`.claude/\` only. Managed by fosh-labs/skills —"
  echo "skills/rules not in \`.claude/skills/.managed\` are project-specific and preserved."
} > "$CURSOR_RULES/$META_RULE"
INSTALLED_RULES+=("$META_RULE")

# --- write manifest -------------------------------------------------------
{
  echo "# Managed by fosh-labs/skills — do not edit by hand."
  echo "# Skills/rules NOT listed here are project-specific and preserved across syncs."
  echo "type=$TYPE"
  for name in "${INSTALLED_SKILLS[@]}"; do echo "skill:$name"; done
  for rule in "${INSTALLED_CLAUDE_RULES[@]}"; do echo "claude-rule:$rule"; done
  for rule in "${INSTALLED_RULES[@]}"; do echo "rule:$rule"; done
} > "$MANIFEST"

echo "Installed ${#INSTALLED_SKILLS[@]} skills + ${#INSTALLED_CLAUDE_RULES[@]} rules + ${#INSTALLED_RULES[@]} Cursor pointers into $PROJECT_DIR"
echo "Manifest: $MANIFEST"
